development:
  adapter: postgresql
  encoding: unicode
  database: zepoc
  pool: 5
  username: postgres
  password: ml870813

test:
  adapter: postgresql
  encoding: unicode
  database: zepoc
  pool: 5
  username: postgres
  password: ml870813