development:
  adapter: postgresql
  encoding: unicode
  database: jackliang
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: jackliang
  host: localhost
  pool: 5